global:
  dbClusterName: shop-db

backend:
  replicaCount: 1
  image: "skip1987/backend-java"
  tag: "latest"
  port: 8080

auth:
  replicaCount: 1
  image: "skip1987/auth-service-go"
  tag: "latest"
  port: 8081

worker:
  replicaCount: 1
  image: "skip1987/order-worker-python"
  tag: "latest"

frontend:
  replicaCount: 1
  image: "skip1987/frontend-react"
  tag: "latest"
  port: 80

database:
  instances: 2
  storage: "1Gi"

gateway:
  className: "eg"