apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app-container
          image: skip1987/k8s-app:v1
          ports:
            - containerPort: 8080
          env:
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NAME
            - name: DB_HOST
              value: "postgres"
            - name: DB_NAME
              value: "mydb"
            - name: DB_USER
              value: "user"
            - name: DB_PASSWORD
              value: "password"