apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init-policy
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: minio-mc
          image: minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              sleep 5;
              mc alias set myminio http://minio:9000 minioadmin minioadmin;
              mc mb myminio/shop-images || true;
              mc policy set download myminio/shop-images;
              echo "Policy successfully set to download for shop-images bucket!";