apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-python
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker-python
  template:
    metadata:
      labels:
        app: worker-python
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image }}:{{ .Values.worker.tag }}"
          env:
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_HOST
              value: "{{ .Values.global.dbClusterName }}-rw"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.dbClusterName }}-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.dbClusterName }}-app
                  key: password
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"